In [7]:
#NUMPY
#Ques1:Create a 1D numpy array of numbers from 1 to 10. What is the result of adding 5 to each element?
import numpy as np
list=[1,2,3,4,5,6,7,8,9,10]
n=np.array(list)
print(n)
print(n+5)

[ 1  2  3  4  5  6  7  8  9 10]
[ 6  7  8  9 10 11 12 13 14 15]


In [2]:
#Ques2:Create a 3x3 identity matrix using numpy?
import numpy as np;
M=np.identity(3)
print("3X3 Matrix:")
print(M)

3X3 Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
#Ques3:Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), how would you access the element in the second row and third column?
import numpy as np
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array)
print(array[1:2,2:3])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[6]]


In [13]:
#Ques4:How can you reshape a 1D array of shape (12,) into a 3D array of shape (2, 2, 3)?
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2,2,3)
print(newarr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [15]:
#Ques5:How can you create a new array that contains only the even numbers from the array arr = np.array([1, 2, 3, 4, 5, 6])?
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr[1],arr[3],arr[5])


2 4 6


In [16]:
#PANDAS
#Ques1:Create a Dictionary with 10 key value pairs. Now convert this Dictionary to Dataframe using Pandas.
import pandas as pd
dict = {"Name":['A','B','C','D','E','F','G','H','I','J'],"Age":[10,13,12,15,9,16,12,10,8,17]}
df = pd.DataFrame.from_dict(dict)
print(df)

  Name  Age
0    A   10
1    B   13
2    C   12
3    D   15
4    E    9
5    F   16
6    G   12
7    H   10
8    I    8
9    J   17


In [21]:
#Ques2:How can you drop the row with index 3 from the DataFrame df?
import pandas as pd
details = {
    'Name': ['abcd', 'efgh', 'ijkl', 'mnop'],
    'Age': [23, 21, 22, 21],
    'University': ['AKG', 'ABES', 'DU', 'BHU'],
}
df = pd.DataFrame(details, columns=['Name', 'Age', 'University'],
                  index=['1', '2', '3', '4'])
print(df)
new_df=df.drop('3')
print(new_df)

   Name  Age University
1  abcd   23        AKG
2  efgh   21       ABES
3  ijkl   22         DU
4  mnop   21        BHU
   Name  Age University
1  abcd   23        AKG
2  efgh   21       ABES
4  mnop   21        BHU


In [22]:
#Ques3:How do you rename the column "old_name" to "new_name"?
import pandas as pd
data = {'old_name': ['A','B','C'], 'roll_no': [4, 5, 6]}
df = pd.DataFrame(data)
df.columns = ['new_name', 'roll_no']
print(df)

  new_name  roll_no
0        A        4
1        B        5
2        C        6


In [34]:
#Ques4:How do you change the data type of the column "salary" from int to float?
import pandas as pd
data=[34000,45000,67000,28000]
df=pd.DataFrame(data,index=[1,2,3,4])
print(df)
df.astype(float)



       0
1  34000
2  45000
3  67000
4  28000


0
1  34000.0
2  45000.0
3  67000.0
4  28000.0

In [39]:
#Ques5:What method would you use to drop any rows that contain NaN values?
import pandas as pd
df=pd.DataFrame({'A':[1,2,3,None],'B':[4,None,6,7]})
print(df)
new_df=df.dropna()
print(new_df)


     A    B
0  1.0  4.0
1  2.0  NaN
2  3.0  6.0
3  NaN  7.0
     A    B
0  1.0  4.0
2  3.0  6.0
